sudo: required
services:
    - docker
    
before_install:
    - docker build -t djcurtis/docker-react -f Dockerfile.dev .
    
script:
    - docker run djcurtis/docker-react npm run test -- --coverage
    
deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "https://s3.console.aws.amazon.com/s3/#"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
