sudo: required
services:
    - docker
    
before_install:
    - docker build -t djcurtis/docker-react -f Dockerfile.dev .
    
script:
    - docker run djcurtis/docker-react npm run test -- --coverage